services:
  # Backend API service
  - type: web
    name: buddy-backend-testing
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true

  # Frontend service
  - type: static
    name: buddy-frontend-testing
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: buddy-backend-testing
          type: web
          property: url
      - key: NODE_ENV
        value: production
